// <auto-generated />
using ACQuoteTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ACQuoteTracker.Migrations
{
    [DbContext(typeof(QuoteDbContext))]
    [Migration("20200530162015_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("ACQuoteTracker.Models.Quote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuoteText")
                        .HasColumnType("TEXT");

                    b.Property<string>("VillagerName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
